# Generated by Django 5.1.4 on 2025-02-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_songs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="year",
            field=models.IntegerField(),
        ),
    ]
